### ISSUE TITLE
Auto-hide drop-downs on hover out in the UI

### ISSUE THREAD

**Issue by bdre-bda** [WiproOpenSourcePractice/openbdre#412]
Steps to replicate the issue:
1)Clone the code, checkout to **predevelop** branch, follow instructions in README.md to build the codebase. 
2)Login to the UI and examine the drop-down behaviour. Edit the UI code present under **openbdre/md-ui/src/main/webapp/WEB-INF/views/** and enable autho-hide the dropdowns on hovering out.

**Comment by kedarbramhe** [comment]
Hi , can I take up this issue ?

**Comment by bdre-bda** [comment]
Yes, please. let us know if you face any issues building the code.
