### ISSUE TITLE
Column sorting not done properly during Hive Data Load

### ISSUE THREAD

**Issue by bdre-bda** [WiproOpenSourcePractice/openbdre#413]
Steps to replicate the issue:
1)Clone the code, checkout to predevelop branch, follow instructions in README.md to build the codebase.
2)Login to the UI and under Data Ingestion -> Choose Import from RDBMS -> choose a table with 10 or more columns and choose 'Ingest & Hive Load', create the data import jobs.
3)In the Hive load job, examine the properties of the sub process, to check the ordering of the columns, they are currently sorted as string, hence they are being sorted as strings like 1,10,11,12,2,3,4,5,6,7,8,9 (considering there are 12 columns), rather than being sorted as 1,2,3,4,5,6,7,8,9,10,11,12
4)Code to be modified under **openbdre/etl-driver/src/main/java/com/wipro/ats/bdre/im/etl/api/**

**Comment by cunhazera** [comment]
Are you talking about the variable `columns` from this line https://github.com/WiproOpenSourcePractice/openbdre/blob/develop/etl-driver/src/main/java/com/wipro/ats/bdre/im/etl/api/CreateRawBaseTables.java#L60 ?

**Comment by bdre-bda** [comment]
@cunhazera Yes, that seems to be the one, would suggest you to build the code and test it with a mysql table containing more than 10 columns. Please raise a pull request to **predevelop** branch once you're done. Please let us know if you face any issues while building the code.

**Comment by cunhazera** [comment]
@bdre-bda can you tell me how to build the project locally?
I could not execute a `mvn clean install`

**Comment by bdre-bda** [comment]
You need to do a mvn clean install -s settings.xml -P<profile>

you may use **cdh52** or **hdp22** based on your hadoop installation. I recommend you to follow the instructions under **Installation** section to build the project.
